# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.  All rights reserved.
# The contributor(s) of this file has/have agreed to the RapidStream Contributor License Agreement.

repos:
  ############################
  #  Built-in Common Checks  #
  ############################

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=4
      - id: trailing-whitespace

  #####################
  #  Auto Formatting  #
  #####################

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/aio-libs/sort-all
    rev: v1.2.0
    hooks:
      - id: sort-all

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  #############
  #  Linting  #
  #############

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        types_or: [asciidoc, python, markdown, rst]
        additional_dependencies: [tomli]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy

  ###############
  #  Copyright  #
  ###############

  - repo: https://github.com/google/pre-commit-tool-hooks
    rev: v1.2.4
    hooks:
      - id: check-links
      - id: check-copyright
        args:
          - --copyright
          - |+
            Copyright (c) YYYY RapidStream Design Automation, Inc. and contributors.  All rights reserved.
            The contributor(s) of this file has/have agreed to the RapidStream Contributor License Agreement.
          - --skip_pattern
          - "(?:\
            ^LICENSE|\
            .*/design/.*|\
            \\.(?:ico|json|v|sv|vhd|bin|tcl|rst|xci|xml|csv|rpt|bd|ini|ipynb|lock|gitignore|c|cpp|tar)\
            )$"
