# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.  All rights reserved.
# The contributor(s) of this file has/have agreed to the RapidStream Contributor License Agreement.

name: Pre-Commit Checks

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout myself
        uses: actions/checkout@v4

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
        shell: bash
